notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
language: c
compiler:
  - gcc
  - clang
install:
  - tool/travis/install.sh
before_script:
  - rvm use 2.3.1
  - tool/travis/before_script.sh
script:
  - test/run-test.sh
